name: api-golang-base

x-logging: &default-logging
  driver: json-file
  options:
      max-size: "100k"
      max-file: "1"

networks:
  shared-services:
      external: true

services:
  server:
    container_name: api-golang-base-server
    image: api-golang-base-server
    build:
      context: ../
      target: build
      dockerfile: ./docker/Dockerfile
      args:
         BUILD_WITH_RACE_DETECTION: $BUILD_WITH_RACE_DETECTION
    env_file:
      - ./.env
    volumes:
      - ../:/app
    ports:
      - 4431:80
    networks:
      - shared-services
    logging: *default-logging
    restart: always
    command: sh -c "if [ \"$WATCH_FILES\" = \"1\" ]; then air; else /usr/local/bin/main; fi"
